(function(){
  var MEALS=["早","午","晚","加"], CHIPS=["白飯半碗","白切鴻","蒸魚","蛋兩隻","豆漿","香蕉","鴾胸","豆腐","菜心","麥皮","熱小米粥"];
  CHIPS[6]="鴾胸".replace("鴾","雞");
  var meal="午";
  function hkDate(){return new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Hong_Kong"});}
  function wd(){return new Date().toLocaleString("en-US",{timeZone:"Asia/Hong_Kong",weekday:"short"}).slice(0,3);}
  function load(){try{return JSON.parse(localStorage.getItem("yipmma-v1")||"{}");}catch(e){return {};}}
  function save(s){s.v=1;s.at=Date.now();s.date=hkDate();localStorage.setItem("yipmma-v1",JSON.stringify(s));}
  function st(){var s=load();s.profile=s.profile||{};s.foods=s.foods||[];s.reports=s.reports||[];s.runs=s.runs||[];s.scans=s.scans||[];s.weights=s.weights||[];s.remarks=s.remarks||{};return s;}
  function latestScan(s){var a=s.scans||[];return a.length?a[a.length-1]:null;}
  function todayFoods(s){var d=hkDate();return (s.foods||[]).filter(function(x){return x.date===d;});}
  function renderMeals(){var box=document.getElementById("meals");box.innerHTML="";MEALS.forEach(function(m){var b=document.createElement("button");b.className="ghost chip"+(m===meal?" on":"");b.textContent=m;b.onclick=function(){meal=m;renderMeals();};box.appendChild(b);});}
  function renderChips(){var box=document.getElementById("chips");box.innerHTML="";CHIPS.forEach(function(c){var b=document.createElement("button");b.className="ghost chip";b.textContent=c;b.onclick=function(){addFood(c);};box.appendChild(b);});}
  function renderFood(){var s=st(),list=document.getElementById("foodList"),arr=todayFoods(s);list.innerHTML="";if(!arr.length){list.innerHTML="<li class='muted'>未記。食完即加。</li>";return;}arr.forEach(function(x){var li=document.createElement("li");li.innerHTML="<span><span class='muted'>"+x.meal+"</span> "+x.text+"</span>";var d=document.createElement("button");d.className="del";d.textContent="刪";d.onclick=function(){var s=st();s.foods=(s.foods||[]).filter(function(f){return f.id!==x.id;});save(s);renderFood();};li.appendChild(d);list.appendChild(li);});}
  function addFood(text){text=(text||document.getElementById("food").value||"").trim();if(!text)return;var s=st();s.foods.push({id:Date.now()+"-"+Math.random().toString(16).slice(2),date:hkDate(),meal:meal,text:text});s.foods=s.foods.slice(-400);save(s);document.getElementById("food").value="";renderFood();}
  function paintScan(){var s=st(),sc=latestScan(s),p=s.profile||{};document.getElementById("h").value=p.heightCm||168;document.getElementById("t").value=p.targetKg||p.boxingTargetKg||54.5;if(!sc){document.getElementById("sum").textContent="未有體脂磅紀錄。";return;}document.getElementById("kg").textContent=(sc.kg||s.lastKg||"—")+" kg";document.getElementById("bf").textContent=(sc.bodyFatPct!=null?sc.bodyFatPct+"%":"—");document.getElementById("mk").textContent=(sc.muscleKg!=null?sc.muscleKg+" kg":"—");document.getElementById("bmr").textContent=sc.bmr||"—";var tgt=Number(p.targetKg||54.5),kg=Number(sc.kg||0),gap=(kg&&tgt)?(kg-tgt).toFixed(2):"—";document.getElementById("sum").textContent="高過目標 "+tgt+" kg "+gap+" kg。";}
  function payload(){var s=st(),sc=latestScan(s)||{},p=s.profile||{};var day={Sun:"恢復",Mon:"滑步",Tue:"Pivot",Wed:"架勢",Thu:"環繞",Fri:"刺拳",Sat:"移動"}[wd()]||"";return{date:hkDate(),weekday:wd(),todaySkill:day,heightCm:Number(document.getElementById("h").value||168),boxingTargetKg:Number(document.getElementById("t").value||54.5),scan:sc,lastKg:s.lastKg||sc.kg,foodsToday:todayFoods(s),journeyRemark:(s.remarks||{})[hkDate()]||document.getElementById("remark").value||"",lastRun:(s.runs||[]).slice(-1)[0]||null,program:"每日 30 分：洛馬 15 + A-E 15。禁止帶氧熱身。每週最多一次 9 分鐘跑。"};}
  function localReport(d){var kg=d.lastKg,tgt=d.boxingTargetKg,foods=d.foodsToday.map(function(x){return x.meal+x.text;}).join("、")||"未記食";var r=d.journeyRemark||"無 remark";var gap=kg&&tgt?(Number(kg)-Number(tgt)).toFixed(2):"?";var lean=/粥|魚|鴻|蛋|豆腐|菜/.test(foods);var junk=/汽水|炸|甜品|奶茶|啤酒|酒/.test(foods+r);return ["1) 而家狀態 / Now",kg?("體重 "+kg+" kg，距目標 "+tgt+" kg 差 "+gap+" kg。"):"仍未入今日磅。","Remark："+r,"","2) 同身高 / 目標","外圍型要輕、有肌。體脂低就唔好猜飢；守肌肉。","","3) 飲食 / Food","今日："+foods+"。"+(junk?"甜飲／炸物偏多，明日換蒸魚或白切鴻。":(lean?"方向對：蛋白 + 粥 + 半碗飯。":"加蛋白，練完先熱小米粥。")),"明日：早蛋兩隻；練後粥+鴾胸；晚蒸魚半碗飯。","","4) 9 分鐘跑",d.lastRun?"已有距離。只係分析，唔好每日加跑。":"本週任一日測一次。唔取代主課。","","5) 訓練","今日技術："+d.todaySkill+"。上半 15 分洛馬，後半 A-E 各 3 組。超哥：唔好做帶氧。"].join("\n");}
  async function llm(d){var key=(document.getElementById("key").value||localStorage.getItem("yipmma-openrouter-key")||"").trim();if(key)localStorage.setItem("yipmma-openrouter-key",key);if(!key)return{ok:true,text:localReport(d),via:"local"};var sys="你是香港私人教練兼營養顧問。繁體中文口語。"+d.heightCm+"cm 男性業餘外圍拳擊。每日洛馬 15 + A-E 15。禁止帶氧熱身。每週最多一次 9 分鐘跑。五段：1 狀態+包 remark 2 目標 3 飲食 4 九分鐘 5 訓練。守肌肉。";try{var res=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+key,"HTTP-Referer":"https://yip-lgtm.github.io/yipmma/","X-Title":"outboxing stance"},body:JSON.stringify({model:"minimax/minimax-m3:free",max_tokens:1200,temperature:.4,messages:[{role:"system",content:sys},{role:"user",content:JSON.stringify(d)}]})});var j=await res.json();var text=j.choices&&j.choices[0]&&j.choices[0].message&&j.choices[0].message.content;if(!res.ok)return{ok:false,error:(j.error&&j.error.message)||("OpenRouter "+res.status)};if(!text)return{ok:false,error:"OpenRouter empty"};return{ok:true,text:text.trim(),via:"llm"};}catch(e){return{ok:true,text:localReport(d)+"\n\n(網路失敗，本機分析)",via:"local"};}}
  document.getElementById("saveProf").onclick=function(){var s=st();s.profile=s.profile||{};s.profile.heightCm=Number(document.getElementById("h").value||168);s.profile.targetKg=Number(document.getElementById("t").value||54.5);s.profile.boxingTargetKg=s.profile.targetKg;save(s);};
  document.getElementById("addFood").onclick=function(){addFood();};
  document.getElementById("food").addEventListener("keydown",function(e){if(e.key==="Enter")addFood();});
  document.getElementById("saveRemark").onclick=function(){var s=st();s.remarks=s.remarks||{};s.remarks[hkDate()]=document.getElementById("remark").value.trim();save(s);document.getElementById("remarkOk").textContent="已保存 "+hkDate();};
  document.getElementById("go").onclick=async function(){document.getElementById("err").textContent="";document.getElementById("go").textContent="分析中…";var s=st();s.remarks=s.remarks||{};s.remarks[hkDate()]=document.getElementById("remark").value.trim();save(s);var r=await llm(payload());document.getElementById("go").textContent="產生今日報告";if(!r.ok){document.getElementById("err").textContent=r.error;return;}document.getElementById("report").textContent=r.text;s=st();s.reports=[{date:hkDate(),text:r.text,via:r.via}].concat(s.reports||[]).slice(0,20);save(s);};
  document.getElementById("key").value=localStorage.getItem("yipmma-openrouter-key")||"";
  var s0=st();document.getElementById("remark").value=(s0.remarks||{})[hkDate()]||"";var lastR=(s0.reports||[])[0];if(lastR&&lastR.date===hkDate())document.getElementById("report").textContent=lastR.text;
  renderMeals();renderChips();renderFood();paintScan();
})();
